image: alpine:3.10

before_script:
    - apk add openssh-client

stages:
    - test
    - deploy-staging
    - deploy-demo

test:
    stage: test
    script:
        - echo "No tests"

deploy-staging:
    stage: deploy-staging
    script:
        - echo "Deploy to staging server"
        - echo "$SSH_PRIVATE_KEY" > ./id_rsa
        - chmod 600 ./id_rsa
        - ssh -o StrictHostKeyChecking=no -p"$SSH_PORT" -i ./id_rsa "$SSH_USER"@"$SSH_STAGING_HOST" "$SSH_DEPLOY_SCRIPT"
    only:
        - dev

deploy-demo:
    stage: deploy-demo
    script:
        - echo "Deploy to demo server"
        - echo "$SSH_PRIVATE_KEY" > ./id_rsa
        - chmod 600 ./id_rsa
        - ssh -o StrictHostKeyChecking=no -p"$SSH_PORT" -i ./id_rsa "$SSH_USER"@"$SSH_DEMO_HOST" "$SSH_DEPLOY_SCRIPT"
    when: manual
    only:
        - master
