version: '3.7'

volumes:
  Magento2DataVolume:

services:
  mysql:
    build:
      context: ./.docker/mysql
      dockerfile: Dockerfile
    command: [--innodb-use-native-aio=0]
    container_name: magento2-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PASSWORD=passwoRt
      - MYSQL_USER=magento2
      - MYSQL_DATABASE=magento2
    volumes:
      - './.docker/mysql/data:/var/lib/mysql'

  php:
    privileged: true
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - 'Magento2DataVolume:/var/www/magento2'
      - '.:/var/www/magento2/app/code/Calcurates/ModuleMagento'
      - './vendor:/var/www/magento2/vendor'
    container_name: magento2-php
    ports:
      - "9000:9000"
    environment:
      - MYSQL_PASSWORD=passwoRt
      - MYSQL_USER=magento2
      - MYSQL_DATABASE=magento2
    depends_on:
      - mysql

  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    volumes:
      - 'Magento2DataVolume:/var/www/magento2'
      - '.:/var/www/magento2/app/code/Calcurates/ModuleMagento'
    ports:
      - "80:80"
    container_name: magento2-nginx
    depends_on:
      - php
